# ==================
# Project Details
# ==================
name: "dbt_expectations"
config-version: 2
require-dbt-version:
- ">=1.2.0"
- "<2.0.0"
version: "0.6.0"

# ==================
# File Path Configs
# ==================
clean-targets:
- "target"
- "dbt_packages"
model-paths:
- "prophecy-sources"
log-path: "logs"
macro-paths:
- "macros"
target-path: "target"
